### ISSUE TITLE
Remove user button

### ISSUE THREAD

**Issue by NirmalMulji** [sbangalore/android-gym-project#19]
The remove user functionality in DashboardFragment.kt line 96 is incomplete

<img width="954" alt="Screen Shot 2020-11-20 at 3 05 30 PM" src="https://user-images.githubusercontent.com/6621180/99849887-f77d8880-2b41-11eb-95fd-822b0e668594.png">

**Comment by sbangalore** [comment]
Solved in most recent pulls.
